name: Build the game

on:
  push:
    branches: [pe-0.6.3-dev]
  pull_request:
    branches: [pe-0.6.3-dev]
  workflow_dispatch:
jobs:
  BuildDesktop:
    name: ${{ matrix.name }}
    permissions: write-all
    strategy:
      matrix:
        include:
          - name: Windows
            os: windows-2022
            buildArgs: windows
            exportPath: windows
            artifactName: P-Slice.0.6.3.windows
            cacheLibrariesPath: P-Slice.0.6.3.desktop-cache
            cachePath: P-Slice.0.6.3.build-windows
            artifactPath: export\PE0.6.3\release\windows\bin\*
          - name: Linux
            os: ubuntu-22.04
            buildArgs: linux
            exportPath: linux
            artifactName: P-Slice.0.6.3.linux
            cachePath: P-Slice.0.6.3.build-linux
            artifactPath: export/PE0.6.3/release/linux/bin/*
            cacheLibrariesPath: P-Slice.0.6.3.desktop-cache

    uses: ./.github/workflows/build.yml
    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      buildArgs: ${{ matrix.buildArgs }}
      cacheLibrariesPath: ${{ matrix.cacheLibrariesPath }}
      exportPath: ${{ matrix.exportPath }}
      artifactName: ${{ matrix.artifactName }}
      artifactPath: ${{ matrix.artifactPath }}
      cachePath: ${{matrix.cachePath}}
  BuildMobile:
    permissions: write-all
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Android
            os: macos-15
            exportPath: android
            buildArgs: "android"
            cacheLibrariesPath: P-Slice.0.6.3.mobile-cache
            artifactName: P-Slice.0.6.3.android
            cachePath: P-Slice.0.6.3.build-android
            artifactPath: "export/PE0.6.3/release/android/bin/app/build/outputs/apk/release/*.apk"

          - name: iOS
            os: macos-15
            buildArgs: "ios -nosign"
            exportPath: ios
            cacheLibrariesPath: P-Slice.0.6.3.mobile-cache
            artifactName: P-Slice.0.6.3.ios
            artifactPath: "export/PE0.6.3/release/ios/build/Release-iphoneos/*.ipa"
            cachePath: P-Slice.0.6.3.build-ios
    uses: ./.github/workflows/build.yml
    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      buildArgs: ${{ matrix.buildArgs }}
      exportPath: ${{ matrix.exportPath }}
      artifactName: ${{ matrix.artifactName }}
      cacheLibrariesPath: ${{ matrix.cacheLibrariesPath }}
      artifactPath: ${{ matrix.artifactPath }}
      cachePath: ${{matrix.cachePath}}
