name: Build deps (0.6.3)
on:
  workflow_dispatch:

jobs:
  BuildCaches:
    name: ${{ matrix.name }}
    permissions: write-all
    strategy:
      matrix:
        include:
          - name: Windows
            os: windows-latest
            setupScript: .\"setup/windows.bat"
            CACHE_NAME: P-Slice.0.6.3.desktop-cache

          - name: Mobile
            os: macos-latest
            setupScript: sh ./setup/mobile.sh
            CACHE_NAME: P-Slice.0.6.3.mobile-cache
    uses: ./.github/workflows/dependencies.yml
    with:
      os: ${{ matrix.os }}
      CACHE_NAME: ${{ matrix.CACHE_NAME }}
      setupScript: ${{ matrix.setupScript }}